@file:Suppress("warnings")
/*
 * This file is generated by jOOQ.
 */
package tessa.jooq.keys


import org.jooq.ForeignKey
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.QOM.ForeignKeyRule

import tessa.jooq.tables.AssetTree
import tessa.jooq.tables.AssetVariant
import tessa.jooq.tables.records.AssetTreeRecord
import tessa.jooq.tables.records.AssetVariantRecord



// -------------------------------------------------------------------------
// UNIQUE and PRIMARY KEY definitions
// -------------------------------------------------------------------------

val ASSET_TREE_PKEY: UniqueKey<AssetTreeRecord> = Internal.createUniqueKey(AssetTree.ASSET_TREE, DSL.name("asset_tree_pkey"), arrayOf(AssetTree.ASSET_TREE.ID), true)
val ASSET_VARIANT_PKEY: UniqueKey<AssetVariantRecord> = Internal.createUniqueKey(AssetVariant.ASSET_VARIANT, DSL.name("asset_variant_pkey"), arrayOf(AssetVariant.ASSET_VARIANT.ID), true)

// -------------------------------------------------------------------------
// FOREIGN KEY definitions
// -------------------------------------------------------------------------

val ASSET_VARIANT__FK_ASSET_VARIANT_ASSET_ID_ASSET_TREE_ID: ForeignKey<AssetVariantRecord, AssetTreeRecord> = Internal.createForeignKey(AssetVariant.ASSET_VARIANT, DSL.name("fk_asset_variant_asset_id_asset_tree_id"), arrayOf(AssetVariant.ASSET_VARIANT.ASSET_ID), tessa.jooq.keys.ASSET_TREE_PKEY, arrayOf(AssetTree.ASSET_TREE.ID), true, ForeignKeyRule.CASCADE, ForeignKeyRule.NO_ACTION)
