@file:Suppress("warnings")
/*
 * This file is generated by jOOQ.
 */
package tessa.jooq.keys


import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal

import tessa.jooq.tables.AssetTree
import tessa.jooq.tables.AssetVariant
import tessa.jooq.tables.Migrations
import tessa.jooq.tables.records.AssetTreeRecord
import tessa.jooq.tables.records.AssetVariantRecord
import tessa.jooq.tables.records.MigrationsRecord


// -------------------------------------------------------------------------
// UNIQUE and PRIMARY KEY definitions
// -------------------------------------------------------------------------

val ASSET_TREE_PKEY: UniqueKey<AssetTreeRecord> =
    Internal.createUniqueKey(AssetTree.ASSET_TREE, DSL.name("asset_tree_pkey"), arrayOf(AssetTree.ASSET_TREE.ID), true)
val ASSET_VARIANT_PKEY: UniqueKey<AssetVariantRecord> = Internal.createUniqueKey(
    AssetVariant.ASSET_VARIANT,
    DSL.name("asset_variant_pkey"),
    arrayOf(AssetVariant.ASSET_VARIANT.ID),
    true
)
val MIGRATIONS_PKEY: UniqueKey<MigrationsRecord> = Internal.createUniqueKey(
    Migrations.MIGRATIONS,
    DSL.name("migrations_pkey"),
    arrayOf(Migrations.MIGRATIONS.ID),
    true
)
