/*
 * This file is generated by jOOQ.
 */
package tessa.jooq.tables


import java.time.LocalDateTime
import java.util.UUID

import kotlin.collections.Collection
import kotlin.collections.List

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Index
import org.jooq.InverseForeignKey
import org.jooq.JSONB
import org.jooq.Name
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl

import tessa.jooq.Public
import tessa.jooq.indexes.ASSET_VARIANT_ASSET_ID_IDX
import tessa.jooq.indexes.ASSET_VARIANT_ASSET_ID_ORIGINAL_VARIANT_UQ
import tessa.jooq.keys.ASSET_VARIANT_PKEY
import tessa.jooq.tables.records.AssetVariantRecord


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class AssetVariant(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, AssetVariantRecord>?,
    parentPath: InverseForeignKey<out Record, AssetVariantRecord>?,
    aliased: Table<AssetVariantRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
) : TableImpl<AssetVariantRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.asset_variant</code>
         */
        val ASSET_VARIANT: AssetVariant = AssetVariant()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<AssetVariantRecord> = AssetVariantRecord::class.java

    /**
     * The column <code>public.asset_variant.id</code>.
     */
    val ID: TableField<AssetVariantRecord, UUID?> =
        createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "")

    /**
     * The column <code>public.asset_variant.asset_id</code>.
     */
    val ASSET_ID: TableField<AssetVariantRecord, UUID?> =
        createField(DSL.name("asset_id"), SQLDataType.UUID.nullable(false), this, "")

    /**
     * The column <code>public.asset_variant.object_store_bucket</code>.
     */
    val OBJECT_STORE_BUCKET: TableField<AssetVariantRecord, String?> =
        createField(DSL.name("object_store_bucket"), SQLDataType.CLOB.nullable(false), this, "")

    /**
     * The column <code>public.asset_variant.object_store_key</code>.
     */
    val OBJECT_STORE_KEY: TableField<AssetVariantRecord, String?> =
        createField(DSL.name("object_store_key"), SQLDataType.CLOB.nullable(false), this, "")

    /**
     * The column <code>public.asset_variant.attributes</code>.
     */
    val ATTRIBUTES: TableField<AssetVariantRecord, JSONB?> =
        createField(DSL.name("attributes"), SQLDataType.JSONB.nullable(false), this, "")

    /**
     * The column <code>public.asset_variant.original_variant</code>.
     */
    val ORIGINAL_VARIANT: TableField<AssetVariantRecord, Boolean?> =
        createField(DSL.name("original_variant"), SQLDataType.BOOLEAN.nullable(false), this, "")

    /**
     * The column <code>public.asset_variant.created_at</code>.
     */
    val CREATED_AT: TableField<AssetVariantRecord, LocalDateTime?> =
        createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "")

    private constructor(alias: Name, aliased: Table<AssetVariantRecord>?) : this(
        alias,
        null,
        null,
        null,
        aliased,
        null,
        null
    )

    private constructor(alias: Name, aliased: Table<AssetVariantRecord>?, parameters: Array<Field<*>?>?) : this(
        alias,
        null,
        null,
        null,
        aliased,
        parameters,
        null
    )

    private constructor(alias: Name, aliased: Table<AssetVariantRecord>?, where: Condition?) : this(
        alias,
        null,
        null,
        null,
        aliased,
        null,
        where
    )

    /**
     * Create an aliased <code>public.asset_variant</code> table reference
     */
    constructor(alias: String) : this(DSL.name(alias))

    /**
     * Create an aliased <code>public.asset_variant</code> table reference
     */
    constructor(alias: Name) : this(alias, null)

    /**
     * Create a <code>public.asset_variant</code> table reference
     */
    constructor() : this(DSL.name("asset_variant"), null)

    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getIndexes(): List<Index> =
        listOf(ASSET_VARIANT_ASSET_ID_IDX, ASSET_VARIANT_ASSET_ID_ORIGINAL_VARIANT_UQ)

    override fun getPrimaryKey(): UniqueKey<AssetVariantRecord> = ASSET_VARIANT_PKEY
    override fun `as`(alias: String): AssetVariant = AssetVariant(DSL.name(alias), this)
    override fun `as`(alias: Name): AssetVariant = AssetVariant(alias, this)
    override fun `as`(alias: Table<*>): AssetVariant = AssetVariant(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): AssetVariant = AssetVariant(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): AssetVariant = AssetVariant(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): AssetVariant = AssetVariant(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): AssetVariant =
        AssetVariant(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): AssetVariant = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): AssetVariant = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): AssetVariant = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL
    override fun where(condition: SQL): AssetVariant = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL
    override fun where(@Stringly.SQL condition: String): AssetVariant = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL
    override fun where(@Stringly.SQL condition: String, vararg binds: Any?): AssetVariant =
        where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL
    override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): AssetVariant =
        where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): AssetVariant = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): AssetVariant = where(DSL.notExists(select))
}
