/*
 * This file is generated by jOOQ.
 */
package tessa.jooq.tables


import kotlin.collections.Collection

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl

import tessa.jooq.Public
import tessa.jooq.keys.MIGRATIONS_PKEY
import tessa.jooq.tables.records.MigrationsRecord


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class Migrations(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, MigrationsRecord>?,
    parentPath: InverseForeignKey<out Record, MigrationsRecord>?,
    aliased: Table<MigrationsRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
) : TableImpl<MigrationsRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.migrations</code>
         */
        val MIGRATIONS: Migrations = Migrations()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<MigrationsRecord> = MigrationsRecord::class.java

    /**
     * The column <code>public.migrations.id</code>.
     */
    val ID: TableField<MigrationsRecord, Long?> =
        createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false), this, "")

    /**
     * The column <code>public.migrations.description</code>.
     */
    val DESCRIPTION: TableField<MigrationsRecord, String?> =
        createField(DSL.name("description"), SQLDataType.CLOB, this, "")

    private constructor(alias: Name, aliased: Table<MigrationsRecord>?) : this(
        alias,
        null,
        null,
        null,
        aliased,
        null,
        null
    )

    private constructor(alias: Name, aliased: Table<MigrationsRecord>?, parameters: Array<Field<*>?>?) : this(
        alias,
        null,
        null,
        null,
        aliased,
        parameters,
        null
    )

    private constructor(alias: Name, aliased: Table<MigrationsRecord>?, where: Condition?) : this(
        alias,
        null,
        null,
        null,
        aliased,
        null,
        where
    )

    /**
     * Create an aliased <code>public.migrations</code> table reference
     */
    constructor(alias: String) : this(DSL.name(alias))

    /**
     * Create an aliased <code>public.migrations</code> table reference
     */
    constructor(alias: Name) : this(alias, null)

    /**
     * Create a <code>public.migrations</code> table reference
     */
    constructor() : this(DSL.name("migrations"), null)

    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getPrimaryKey(): UniqueKey<MigrationsRecord> = MIGRATIONS_PKEY
    override fun `as`(alias: String): Migrations = Migrations(DSL.name(alias), this)
    override fun `as`(alias: Name): Migrations = Migrations(alias, this)
    override fun `as`(alias: Table<*>): Migrations = Migrations(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): Migrations = Migrations(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): Migrations = Migrations(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): Migrations = Migrations(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): Migrations =
        Migrations(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): Migrations = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): Migrations = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): Migrations = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL
    override fun where(condition: SQL): Migrations = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL
    override fun where(@Stringly.SQL condition: String): Migrations = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL
    override fun where(@Stringly.SQL condition: String, vararg binds: Any?): Migrations =
        where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL
    override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): Migrations =
        where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): Migrations = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): Migrations = where(DSL.notExists(select))
}
