/*
 * This file is generated by jOOQ.
 */
package tessa.jooq


import org.jooq.Catalog
import org.jooq.Table
import org.jooq.impl.DSL
import org.jooq.impl.SchemaImpl
import tessa.jooq.tables.AssetTree
import tessa.jooq.tables.AssetVariant


/**
 * standard public schema
 */
@Suppress("warnings")
open class Public : SchemaImpl(DSL.name("public"), DefaultCatalog.DEFAULT_CATALOG, DSL.comment("standard public schema")) {
    companion object {

        /**
         * The reference instance of <code>public</code>
         */
        val PUBLIC: Public = Public()
    }

    /**
     * The table <code>public.asset_tree</code>.
     */
    val ASSET_TREE: AssetTree get() = AssetTree.ASSET_TREE

    /**
     * The table <code>public.asset_variant</code>.
     */
    val ASSET_VARIANT: AssetVariant get() = AssetVariant.ASSET_VARIANT

    override fun getCatalog(): Catalog = DefaultCatalog.DEFAULT_CATALOG

    override fun getTables(): List<Table<*>> = listOf(
        AssetTree.ASSET_TREE,
        AssetVariant.ASSET_VARIANT
    )
}
