/*
 * This file is generated by jOOQ.
 */
package tessa.jooq.routines


import org.jooq.Field
import org.jooq.Parameter
import org.jooq.impl.AbstractRoutine
import org.jooq.impl.DSL
import org.jooq.impl.DefaultDataType
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.postgres.extensions.bindings.LtreeArrayBinding

import tessa.jooq.Public


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class _LtQRregex : AbstractRoutine<Boolean>("_lt_q_rregex", Public.PUBLIC, DSL.comment(""), SQLDataType.BOOLEAN) {
    companion object {

        /**
         * The parameter <code>public._lt_q_rregex.RETURN_VALUE</code>.
         */
        val RETURN_VALUE: Parameter<Boolean?> = Internal.createParameter("RETURN_VALUE", SQLDataType.BOOLEAN, false, false)

        /**
         * The parameter <code>public._lt_q_rregex._1</code>.
         */
        val _1: Parameter<Array<Any?>?> = Internal.createParameter("_1", DefaultDataType.getDefaultDataType("\"public\".\"lquery\"").array(), false, true)

        /**
         * The parameter <code>public._lt_q_rregex._2</code>.
         */
        val _2: Parameter<Array<org.jooq.postgres.extensions.types.Ltree?>?> = Internal.createParameter("_2", DefaultDataType.getDefaultDataType("\"public\".\"ltree\"").array(), false, true, LtreeArrayBinding())
    }

    init {
        returnParameter = _LtQRregex.RETURN_VALUE
        addInParameter(_LtQRregex._1)
        addInParameter(_LtQRregex._2)
    }

    /**
     * Set the <code>_1</code> parameter IN value to the routine
     */
    fun set__1(value: Array<Any?>?): Unit = setValue(_LtQRregex._1, value)

    /**
     * Set the <code>_1</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    fun set__1(field: Field<Array<Any?>?>): Unit {
        setField(_LtQRregex._1, field)
    }

    /**
     * Set the <code>_2</code> parameter IN value to the routine
     */
    fun set__2(value: Array<org.jooq.postgres.extensions.types.Ltree?>?): Unit = setValue(_LtQRregex._2, value)

    /**
     * Set the <code>_2</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    fun set__2(field: Field<Array<org.jooq.postgres.extensions.types.Ltree?>?>): Unit {
        setField(_LtQRregex._2, field)
    }
}
