/*
 * This file is generated by jOOQ.
 */
package tessa.jooq.routines


import org.jooq.Field
import org.jooq.Parameter
import org.jooq.impl.AbstractRoutine
import org.jooq.impl.DSL
import org.jooq.impl.DefaultDataType
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.postgres.extensions.bindings.LtreeBinding
import org.jooq.postgres.extensions.types.Ltree

import tessa.jooq.Public


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class Index1 : AbstractRoutine<Int>("index", Public.PUBLIC, DSL.comment(""), SQLDataType.INTEGER) {
    companion object {

        /**
         * The parameter <code>public.index.RETURN_VALUE</code>.
         */
        val RETURN_VALUE: Parameter<Int?> = Internal.createParameter("RETURN_VALUE", SQLDataType.INTEGER, false, false)

        /**
         * The parameter <code>public.index._1</code>.
         */
        val _1: Parameter<Ltree?> = Internal.createParameter("_1", DefaultDataType.getDefaultDataType("\"public\".\"ltree\""), false, true, LtreeBinding())

        /**
         * The parameter <code>public.index._2</code>.
         */
        val _2: Parameter<Ltree?> = Internal.createParameter("_2", DefaultDataType.getDefaultDataType("\"public\".\"ltree\""), false, true, LtreeBinding())
    }

    init {
        returnParameter = Index1.RETURN_VALUE
        addInParameter(Index1._1)
        addInParameter(Index1._2)
        setOverloaded(true)
    }

    /**
     * Set the <code>_1</code> parameter IN value to the routine
     */
    fun set__1(value: Ltree?): Unit = setValue(Index1._1, value)

    /**
     * Set the <code>_1</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    fun set__1(field: Field<Ltree?>): Unit {
        setField(Index1._1, field)
    }

    /**
     * Set the <code>_2</code> parameter IN value to the routine
     */
    fun set__2(value: Ltree?): Unit = setValue(Index1._2, value)

    /**
     * Set the <code>_2</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    fun set__2(field: Field<Ltree?>): Unit {
        setField(Index1._2, field)
    }
}
