/*
 * This file is generated by jOOQ.
 */
package tessa.jooq.routines


import org.jooq.Field
import org.jooq.Parameter
import org.jooq.impl.AbstractRoutine
import org.jooq.impl.DSL
import org.jooq.impl.DefaultDataType
import org.jooq.impl.Internal
import org.jooq.postgres.extensions.bindings.LtreeBinding
import org.jooq.postgres.extensions.types.Ltree

import tessa.jooq.Public


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class LtreeIn : AbstractRoutine<Ltree>("ltree_in", Public.PUBLIC, DSL.comment(""), DefaultDataType.getDefaultDataType("\"public\".\"ltree\""), LtreeBinding()) {
    companion object {

        /**
         * The parameter <code>public.ltree_in.RETURN_VALUE</code>.
         */
        val RETURN_VALUE: Parameter<Ltree?> = Internal.createParameter("RETURN_VALUE", DefaultDataType.getDefaultDataType("\"public\".\"ltree\""), false, false, LtreeBinding())
        @Deprecated(message = "Unknown data type. If this is a qualified, user-defined type, it may have been excluded from code generation. If this is a built-in type, you can define an explicit org.jooq.Binding to specify how this type should be handled. Deprecation can be turned off using <deprecationOnUnknownTypes/> in your code generator configuration.")
        val _1: Parameter<Any?> = Internal.createParameter("_1", DefaultDataType.getDefaultDataType("\"pg_catalog\".\"cstring\""), false, true)
    }

    init {
        returnParameter = LtreeIn.RETURN_VALUE
        addInParameter(LtreeIn._1)
    }

    /**
     * Set the <code>_1</code> parameter IN value to the routine
     */
    fun set__1(value: Any?): Unit = setValue(LtreeIn._1, value)

    /**
     * Set the <code>_1</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    fun set__1(field: Field<Any?>): Unit {
        setField(LtreeIn._1, field)
    }
}
