@file:Suppress("warnings")
/*
 * This file is generated by jOOQ.
 */
package tessa.jooq.tables.references


import tessa.jooq.tables.AssetTree
import tessa.jooq.tables.AssetVariant
import tessa.jooq.tables.Migrations


/**
 * The table <code>public.asset_tree</code>.
 */
val ASSET_TREE: AssetTree = AssetTree.ASSET_TREE

/**
 * The table <code>public.asset_variant</code>.
 */
val ASSET_VARIANT: AssetVariant = AssetVariant.ASSET_VARIANT

/**
 * The table <code>public.migrations</code>.
 */
val MIGRATIONS: Migrations = Migrations.MIGRATIONS
